export const products = [
  {
    id: "box-lunch",
    title: "Box Lunch",
    description: "Perfect individual meals for any gathering.",
    priceValue: 12,
    imageSrc: "/images/hot-dog.png",
    category: "Meals",
    badge: "Popular",
    inStock: true,
    serves: "Per person",
  },
  {
    id: "party-tray",
    title: "Party Tray",
    description: "Feeds the whole crowd with ease.",
    priceValue: 45,
    imageSrc: "/images/pretzel.png",
    category: "Trays",
    inStock: true,
    serves: "Serves 8–10",
  },
   {
    id: "Sandwich Platter",
    title: "Party Platter",
    description: "You are going to love this!",
    priceValue: 30,
    imageSrc: "/images/bologna.png",
    category: "Trays",
    inStock: true,
    serves: "Serves 8–10",
  },
];
